# Copyright (C) ShapeBlue Ltd - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Released by ShapeBlue <info@shapeblue.com>, April 2014

---
- name: Ensure selinux python bindings are installed
  yum: name=libselinux-python state=present
  
- name: Ensure the Apache Cloudstack Repo file is configured
  template: src=cloudstack.repo.j2 dest=/etc/yum.repos.d/cloudstack.repo

- name: Ensure GPGKey is installed
  rpm_key: state=present key={{ item }}
  with_items:
  - http://packages.shapeblue.com/release.asc

- name: Set selinux to permissive
  command: setenforce permissive
  changed_when: false
  
- name: Ensure selinux is set permanently
  selinux: policy=targeted state=permissive

- name: Ensure CloudStack packages are installed
  yum: name=cloudstack-management state=present

- name: Ensure vhd-util is present
  get_url: url="http://download.cloud.com.s3.amazonaws.com/tools/vhd-util" dest="/usr/share/cloudstack-common/scripts/vm/hypervisor/xenserver/vhd-util" mode=0755

- include: ./setupdb.yml

- name: Ensure CloudStack Usage Service is installed
  yum: name=cloudstack-usage state=present
  
- name: Ensure CloudStack Usage Service is started
  service: name=cloudstack-usage state=started
